import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  // js .map()
const items = [
  "Comment✏️","Award🏆","Share📤","Save🏷️"
]

const nums = [1,2,3,4,5]
const numsMultiplyTwo = nums.map(num=> num * 2) // [2,4,6,8,10]
console.log(numsMultiplyTwo);

const newItems = items.map(item => item)

console.log(newItems);

const buttonArr = items.map(function (value, index){
  // return "aa" + value + "ss";
  // return 'aa' + value + 'ss';

  return <button key={index} className="btn btn-light btn-sm">{value}</button>
  // return <button key={index} styles="margin:10px !important">{value}</button>


  // return <button key={index} type="button" className="btn btn-secondary btn-sm" >{value}</button>

  // return <button key={index} type="button" className="btn btn-secondary btn-sm" styles="margin:100px !important">{value}</button>

});




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div>
          {buttonArr}
{/* <button  className="btn btn-light">Comment✏️</button>
<button type="button" className="btn btn-secondary btn-sm">Award🏆</button>
<button type="button" className="btn btn-light btn-sm">Share📤</button>
<button type="button" className="btn btn-secondary btn-sm">Save🏷️</button> */}
          
        </div>
      




        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
